### ISSUE TITLE
Segmentation fault + cannot register existing type 'GdkDisplayManager'

### ISSUE THREAD

**Issue by lakrestofer** [Aylur/ags#655]
**Describe the bug**
Ags setup that works in my devshell does not launch correctly when the package has been built and ingested by my flake -> nixos configuration. 

Output when trying to launch the built package:
```
(gjs:209345): GLib-GObject-CRITICAL **: 15:44:11.454: cannot register existing type 'GdkDisplayManager'

(gjs:209345): GLib-CRITICAL **: 15:44:11.454: g_once_init_leave_pointer: assertion 'result != 0' failed

(gjs:209345): GLib-GObject-CRITICAL **: 15:44:11.454: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
zsh: segmentation fault (core dumped)  agsbar
```

**To Reproduce**
Here is my flake describing my nixos + home manager setup. It takes my bar flake as input.

- [Nixos flake](https://github.com/lakrestofer/dotfiles/blob/65344a4cc909ed28673b1c5ea589b404d9de62a6/flake.nix)
- [bar flake](https://github.com/lakrestofer/datni/blob/a105e0b559877fb73459ca5c8646916376e91c0b/flake.nix)

If a more reproducible setups is needed, I'm more than happy to try to provide it (might need some help though). 

**Expected behavior**
The bar that functions correctly in my devshell should work outside it.

**Additional context**
Most definitely an issue with my configuration. I'm a nixos newbie so the issue is probably a simple one.

**Comment by Aylur** [comment]
fixed with https://github.com/Aylur/ags/commit/251d39413543264361898b02035775aa3e46fe52

**Comment by AymanLyesri** [comment]
still having the same issue in v2.3.0

![Image](https://github.com/user-attachments/assets/fc0ebc99-9e7c-4456-a624-55ee4d144db5)

![Image](https://github.com/user-attachments/assets/ceb163ab-06c5-49d4-8d06-83b2df2ab1ff)

here is the main code:

```tsx
import { App } from "astal/gtk3"
import Bar from "./widgets/bar/Bar"
import { getCssPath } from "./utils/scss"
import RightPanel from "./widgets/rightPanel/RightPanel"
import RightPanelHover from "./widgets/rightPanel/RightPanelHover"
import NotificationPopups from "./widgets/NotificationPopups"
import AppLauncher from "./widgets/AppLauncher"
import Progress from "./widgets/Progress"
import UserPanel from "./widgets/UserPanel"
import WallpaperSwitcher from "./widgets/WallpaperSwitcher"
import MediaPopups from "./widgets/MediaPopups"
import SettingsWidget from "./widgets/SettingsWidget"
import BarHover from "./widgets/bar/BarHover"

App.start({
    css: getCssPath(),
    main()
    {
        // Bar()
        // BarHover()

        // RightPanel()
        // RightPanelHover()

        // NotificationPopups()

        // AppLauncher()

        // Progress()

        // UserPanel()

        // WallpaperSwitcher()

        // MediaPopups()

        // SettingsWidget()

        console.log("App started");

    },
})
```

using the default gtk3 works but gtk4 dosent for some reason, pls help
